"""Exercise 1.5"""

def transcription(dna_seq):
    rna_seq = dna_seq.replace("T","U")
    return rna_seq



if __name__ == "__main__":
    print(transcription("GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGT" \
    "AAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTG" \
    "GAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATG" \
    "TAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"))